CREATE TABLE IF NOT EXISTS `geo` (
    idGeo INT AUTO_INCREMENT PRIMARY KEY,
    lat DECIMAL(9,6) NOT NULL,
    lng DECIMAL(9,6) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `address` (
	idAddress INT AUTO_INCREMENT PRIMARY KEY,
    street VARCHAR(255) NOT NULL,
    suit VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    zipcode VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    website VARCHAR(255) NOT NULL,
    idGeo INT NOT NULL,
    FOREIGN KEY(idGeo) REFERENCES geo(idGeo)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `company` (
	idCompany INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    catchPhrase VARCHAR(255) NOT NULL,
    bs VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `users`(
	idUser INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    userName VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
	idAddress INT NOT NULL,
    idCompany INT,
    FOREIGN KEY(idAddress) REFERENCES address(idAddress),
    FOREIGN KEY(idCompany) REFERENCES company(idCompany)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `blogs`(
	idBlog INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    body VARCHAR(255),
    idUser INT NOT NULL,
    FOREIGN KEY(idUser) REFERENCES users(idUser)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
